INSERT INTO `categories` (`id`, `name`, `department`, `category_id`, `url`) VALUES
(1, 'Tratamiento facial', 'tratamientos', NULL, 'facial'),
(2, 'Tratamiento corporal', 'tratamientos', NULL, 'corporal'),
(3, 'Tratamiento de pestañas', 'tratamientos', NULL, 'pestañas'),
(4, 'Manicura y pedicura', 'tratamientos', NULL, 'manicuraypedicura'),
(5, 'Depilaciones', 'tratamientos', NULL, 'depilaciones'),
(6, 'Micro pigmentación', 'tratamientos', NULL, 'micropigmentacion'),
(7, 'Cambio de look', 'tratamientos', NULL, 'cambiolook'),
(8, 'Extensiones', 'tratamientos', 3, 'extensiones'),
(9, 'Lifting', 'tratamientos', 3, 'lifting'),
(10, 'Tinte', 'tratamientos', 3, 'tinte'),
(11, 'Tratamiento de ácido hialurónico', 'tratamientos', 1, 'acidohialuronico'),
(12, 'Tratamiento antiedad', 'tratamientos', 1, 'antiedad'),
(13, 'Mesoterapia facial', 'tratamientos', 1, 'mesoterapiafacial'),
(14, 'Peeling químico', 'tratamientos', 1, 'peelingquimico'),
(15, 'Aumento de labios', 'tratamientos', 1, 'aumentolabios'),
(16, 'Masajes', 'tratamientos', 2, 'masajes'),
(17, 'Carboxiterapia corporal', 'tratamientos', 2, 'carboxiterapia'),
(18, 'Mesoterapia corporal', 'tratamientos', 2, 'mesoterapiacorporal'),
(19, 'Presoterapia', 'tratamientos', 2, 'presoterapia'),
(20, 'Tratamiento anticelulítico', 'tratamientos', 2, 'anticelulitico'),
(21, 'Cuidado facial', 'tienda', NULL, 'cuidadofacial'),
(22, 'Tratamientos', 'tienda', NULL, 'productostratamientos'),
(23, 'Maquillaje', 'tienda', NULL, 'maquillaje'),
(24, 'Uñas', 'tienda', NULL, 'uñas'),
(25, 'Corporal', 'tienda', NULL, 'corporales'),
(26, 'Desmaquillantes', 'tienda', 21, 'desmaquillantes'),
(27, 'Limpiadores', 'tienda', 21, 'limpiadores'),
(28, 'Exfoliantes', 'tienda', 21, 'exfoliantes'),
(29, 'Tónicos', 'tienda', 22, 'tonicos'),
(30, 'Mascarillas', 'tienda', 21, 'mascarillas'),
(31, 'Esencias', 'tienda', 21, 'esencias'),
(32, 'Sérums', 'tienda', 21, 'serums'),
(33, 'Contornos de ojos', 'tienda', 21, 'contornosojos'),
(34, 'Cremas', 'tienda', 21, 'cremas'),
(35, 'Protectores solares', 'tienda', 21, 'solares'),
(36, 'Antiedad', 'tienda', 22, 'productosantiedad'),
(37, 'Poros', 'tienda', 22, 'poros'),
(38, 'Acné', 'tienda', 22, 'acne'),
(39, 'Manchas', 'tienda', 22, 'mancas'),
(40, 'Luminosidad', 'tienda', 22, 'luminosidad'),
(41, 'Labios', 'tienda', 23, 'labios'),
(42, 'Ojos', 'tienda', 23, 'ojos'),
(43, 'Cejas', 'tienda', 23, 'cejas'),
(44, 'Coloretes', 'tienda', 23, 'coloretes'),
(45, 'Prebases', 'tienda', 23, 'prebases'),
(46, 'Bases', 'tienda', 23, 'bases'),
(47, 'Correctores', 'tienda', 23, 'correctores'),
(48, 'Iluminadores', 'tienda', 23, 'iluminadores');
